2025-04-09 10:39:35,946 - ERROR - Failed to send OTP email to tradingsir98@gmail.com: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-22ac7cb4fbcsm2224705ad.182 - gsmtp')
2025-04-09 10:39:35,947 - ERROR - Internal Server Error: /api/account/requestOttp/
2025-04-09 10:44:03,773 - INFO - F:\funding app\backendServer\backendshop\account\v_PasswordRest.py changed, reloading.
2025-04-09 10:44:04,480 - INFO - Watching for file changes with StatReloader
2025-04-09 10:44:15,034 - ERROR - Failed to send OTP email to tradingsir98@gmail.com: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-22ac7b87885sm2418645ad.55 - gsmtp')
2025-04-09 10:44:15,035 - ERROR - Internal Server Error: /api/account/requestOttp/
2025-04-09 10:48:30,189 - ERROR - Failed to send OTP email to tradingsir98@gmail.com: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 98e67ed59e1d1-306dd187263sm543879a91.42 - gsmtp')
2025-04-09 10:48:30,190 - ERROR - Internal Server Error: /api/account/requestOttp/
2025-04-09 10:49:46,861 - INFO - F:\funding app\backendServer\backendshop\backend\settings.py changed, reloading.
2025-04-09 10:49:47,626 - INFO - Watching for file changes with StatReloader
2025-04-09 10:50:29,051 - INFO - F:\funding app\backendServer\backendshop\account\v_PasswordRest.py changed, reloading.
2025-04-09 10:50:29,622 - INFO - Watching for file changes with StatReloader
2025-04-09 10:50:36,695 - INFO - Password reset OTP sent to tradingsir98@gmail.com
2025-04-09 10:53:14,206 - INFO - F:\funding app\backendServer\backendshop\account\v_PasswordRest.py changed, reloading.
2025-04-09 10:53:14,787 - INFO - Watching for file changes with StatReloader
2025-04-09 11:24:43,084 - INFO - F:\funding app\backendServer\backendshop\backend\settings.py changed, reloading.
2025-04-09 12:57:55,258 - INFO - Watching for file changes with StatReloader
2025-04-09 12:59:09,421 - WARNING - Bad Request: /api/account/auth/google/login/
2025-04-09 12:59:20,760 - WARNING - Bad Request: /api/account/auth/google/login/
2025-04-09 13:09:36,329 - INFO - F:\funding app\backendServer\backendshop\backend\settings.py changed, reloading.
2025-04-09 13:09:37,392 - INFO - Watching for file changes with StatReloader
2025-04-09 13:13:55,836 - INFO - F:\funding app\backendServer\backendshop\User\views.py changed, reloading.
2025-04-09 13:13:56,942 - INFO - Watching for file changes with StatReloader
2025-04-09 13:14:07,630 - INFO - F:\funding app\backendServer\backendshop\User\views.py changed, reloading.
2025-04-09 13:14:08,588 - INFO - Watching for file changes with StatReloader
2025-04-09 13:14:54,201 - INFO - F:\funding app\backendServer\backendshop\User\urls.py changed, reloading.
2025-04-09 13:14:55,250 - INFO - Watching for file changes with StatReloader
2025-04-09 13:15:10,072 - INFO - F:\funding app\backendServer\backendshop\backend\settings.py changed, reloading.
2025-04-09 13:15:11,041 - INFO - Watching for file changes with StatReloader
2025-04-09 13:15:28,849 - INFO - F:\funding app\backendServer\backendshop\backend\settings.py changed, reloading.
2025-04-09 13:15:29,907 - INFO - Watching for file changes with StatReloader
2025-04-09 13:17:40,970 - INFO - Watching for file changes with StatReloader
2025-04-09 13:17:55,362 - WARNING - Bad Request: /api/account/auth/google/login/
2025-04-09 13:19:51,290 - WARNING - Bad Request: /api/account/auth/google/login/
2025-04-09 13:22:10,444 - ERROR - Internal Server Error: /api/account/auth/google/login/
Traceback (most recent call last):
  File "F:\funding app\backendServer\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\backendshop\User\GoogleLoginView.py", line 13, in post
    token = request.data.get("token")
            ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
2025-04-09 13:24:07,963 - WARNING - Bad Request: /api/account/auth/google/login/
2025-04-09 13:24:27,440 - WARNING - Bad Request: /api/account/auth/google/login/
2025-04-09 13:26:53,921 - WARNING - Bad Request: /api/account/auth/google/login/
2025-04-09 13:30:25,280 - WARNING - Bad Request: /api/account/auth/google/login/
2025-04-09 13:32:36,527 - ERROR - Internal Server Error: /api/account/auth/google/login/
Traceback (most recent call last):
  File "F:\funding app\backendServer\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\backendshop\User\GoogleLoginView.py", line 13, in post
    token = request.data.get("token")
            ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
2025-04-09 13:35:07,424 - INFO - F:\funding app\backendServer\backendshop\User\GoogleLoginView.py changed, reloading.
2025-04-09 13:35:08,793 - INFO - Watching for file changes with StatReloader
2025-04-09 13:35:12,527 - ERROR - Internal Server Error: /api/account/auth/google/login/
Traceback (most recent call last):
  File "F:\funding app\backendServer\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\backendshop\User\GoogleLoginView.py", line 14, in post
    token = request.data.get("token")
            ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
2025-04-09 13:35:48,360 - WARNING - Not Found: /src/main.tsx
2025-04-09 13:35:48,375 - WARNING - Not Found: /@react-refresh
2025-04-09 13:35:51,169 - WARNING - Not Found: /node_modules/vite/dist/client/env.mjs
2025-04-09 13:35:51,216 - WARNING - Not Found: /favicon.ico
2025-04-09 13:38:59,060 - ERROR - Internal Server Error: /api/account/auth/google/login/
Traceback (most recent call last):
  File "F:\funding app\backendServer\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\backendshop\User\GoogleLoginView.py", line 14, in post
    token = request.data.get("token")
            ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
2025-04-09 13:41:55,440 - INFO - F:\funding app\backendServer\backendshop\User\GoogleLoginView.py changed, reloading.
2025-04-09 13:41:56,747 - INFO - Watching for file changes with StatReloader
2025-04-09 13:42:05,761 - ERROR - Internal Server Error: /api/account/auth/google/login/
Traceback (most recent call last):
  File "F:\funding app\backendServer\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "F:\funding app\backendServer\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\funding app\backendServer\backendshop\User\GoogleLoginView.py", line 14, in post
    token = request.data.get("id_token")
            ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
2025-04-09 13:45:36,828 - WARNING - Bad Request: /api/account/auth/google/login/
2025-04-09 13:46:08,080 - DEBUG - Starting new HTTPS connection (1): www.googleapis.com:443
2025-04-09 13:46:08,408 - DEBUG - https://www.googleapis.com:443 "GET /oauth2/v3/tokeninfo?id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImM3ZTA0NDY1NjQ5ZmZhNjA2NTU3NjUwYzdlNjVmMGE4N2FlMDBmZTgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIxMDQ3NDY0OTQxMjMwLTRmcDdwdjV1bTlsMHMydTBjMHNsaTV1czN2aDJ0bmtnLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiMTA0NzQ2NDk0MTIzMC00ZnA3cHY1dW05bDBzMnUwYzBzbGk1dXMzdmgydG5rZy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjEwMDQwODg1MDcwODgyNzUwNzY1MSIsImVtYWlsIjoidHJhZGluZ3Npcjk4QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYmYiOjE3NDQxODUzNjcsIm5hbWUiOiJUcmFkaW5nIFNpciIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NKaWFrTzM3TGlzeEEyZXd5b1ozei1JU0FtbS1xSTNBM3g1ZFh4T083TWJXQ2t3bGc9czk2LWMiLCJnaXZlbl9uYW1lIjoiVHJhZGluZyIsImZhbWlseV9uYW1lIjoiU2lyIiwiaWF0IjoxNzQ0MTg1NjY3LCJleHAiOjE3NDQxODkyNjcsImp0aSI6IjEwYTdiNTBjZmM0MGNmMTQxMGQ2ZDc4Y2RlNTVlMDA5Y2FiYjczMDAifQ.onoXonWAXRF12yoTIt7hPudVc_bGFykHCSUc6c5_7hBuexgY3oD3zzezK8N5j8DDiWNZ3XeHdEd_guHpc2OG_NZig5yZyH_2FhExQopDB1vDf_geJJFRTOrZc2-VOx88DFtm2V6bCHBCa6TW4FG6LXIS8Sld9O8JPiNFFN-0E78xVrXrkDwDlQMo6oVwT4Sz4V6_lKK3VSec0esbipPXi4MLJdmVGhw2uxYbIYNtBQ6NH_J3tzOkZr13iVyG0JHhOMrupqVFVDP3rNuugaFti56uCiAg4pl9atGo7DoabK2p_XqB6XdVAtkG2JLb7CB1z4S3B64k2IODnv18-fSOBQ HTTP/1.1" 200 None
2025-04-09 14:08:21,813 - INFO - F:\funding app\backendServer\backendshop\User\GoogleLoginView.py changed, reloading.
2025-04-09 14:08:22,988 - INFO - Watching for file changes with StatReloader
2025-04-09 14:09:56,125 - DEBUG - Starting new HTTPS connection (1): www.googleapis.com:443
2025-04-09 14:09:56,478 - DEBUG - https://www.googleapis.com:443 "GET /oauth2/v3/tokeninfo?id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImM3ZTA0NDY1NjQ5ZmZhNjA2NTU3NjUwYzdlNjVmMGE4N2FlMDBmZTgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIxMDQ3NDY0OTQxMjMwLTRmcDdwdjV1bTlsMHMydTBjMHNsaTV1czN2aDJ0bmtnLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiMTA0NzQ2NDk0MTIzMC00ZnA3cHY1dW05bDBzMnUwYzBzbGk1dXMzdmgydG5rZy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjEwMDQwODg1MDcwODgyNzUwNzY1MSIsImVtYWlsIjoidHJhZGluZ3Npcjk4QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYmYiOjE3NDQxODY3OTUsIm5hbWUiOiJUcmFkaW5nIFNpciIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NKaWFrTzM3TGlzeEEyZXd5b1ozei1JU0FtbS1xSTNBM3g1ZFh4T083TWJXQ2t3bGc9czk2LWMiLCJnaXZlbl9uYW1lIjoiVHJhZGluZyIsImZhbWlseV9uYW1lIjoiU2lyIiwiaWF0IjoxNzQ0MTg3MDk1LCJleHAiOjE3NDQxOTA2OTUsImp0aSI6ImQ1ODhmMzQ0ZWZlMGJjZDI5ZTczYmQ1Y2Q5MGNlN2Q2MWI3NjExYmYifQ.vu0Q8gkFSVPBxYaOpM7ZeC_F3Ps5fIa8AI5V727OtcmnsEICobs6ulW4irQ-QCRG_Ba6qlH2I4jJVC2ri23hHJ10-23oF2EsPoHbtrWBJs4OKgi3gmVEGQGHEL_tJ9RCzWh2j_BPRNJZmRT3EQF5z_pV-wCE4trCQ1j_kZEBtsonWr66N93neQqDWgXmUxR1s9p3R7karUDK4pCjfn24w73BaL4EKX-pfO9xOu5D_ew9vjX0hs1iIde6At9at1ZuOsiDPqm94pUO7OsWYqgAvxUM11u2r5xSTwHb_7OiWeWPqWVCz1PbPdlQIk47bs5gvH7Qfttk0-ktWp3exMqvtw HTTP/1.1" 200 None
2025-04-09 14:10:14,896 - DEBUG - Starting new HTTPS connection (1): www.googleapis.com:443
2025-04-09 14:10:15,181 - DEBUG - https://www.googleapis.com:443 "GET /oauth2/v3/tokeninfo?id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImM3ZTA0NDY1NjQ5ZmZhNjA2NTU3NjUwYzdlNjVmMGE4N2FlMDBmZTgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIxMDQ3NDY0OTQxMjMwLTRmcDdwdjV1bTlsMHMydTBjMHNsaTV1czN2aDJ0bmtnLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiMTA0NzQ2NDk0MTIzMC00ZnA3cHY1dW05bDBzMnUwYzBzbGk1dXMzdmgydG5rZy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjExNjAzNTc2NTcyOTIxMjQzNTQ0NCIsImVtYWlsIjoiY29udGVudHBhZ2V3b3Jrc3BhY2UxQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYmYiOjE3NDQxODY4MTQsIm5hbWUiOiJIVWIgQWVyYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLZm1vUjE4VlNQd1NUbHZYQzdmOUVZZWlpeElrQWljZEdjNUJLcG92U0podk5pMlE9czk2LWMiLCJnaXZlbl9uYW1lIjoiSFViIiwiZmFtaWx5X25hbWUiOiJBZXJhIiwiaWF0IjoxNzQ0MTg3MTE0LCJleHAiOjE3NDQxOTA3MTQsImp0aSI6IjRlMzM5NWIyNzFmYzVhNmE5ODk5MDNiMjk0YjViOWY4NzZhNzI2ZTcifQ.QBr0RATdwQ6OIWts6hJ6RgpGpDify_CAd_sV1wP1LJUZecewDXJSiXP6LwML3tkiyGnDkElCeOUbRpfXtVS-DkQx1yrlEp2Kp-UpuJ1O4w1ErBZB0W9Y5moqLsf4BIdgdpW1BpcCMTGZNduAG7gvv3tu8aD5RM72urxUes2fX9gy6TPTRscgJ8AxZCqJh9NRNlUS7E8j056PJ0vyAhQmUiSocRxADKvN37FzSRwGchKAoVkLCF-Y7N6bNRfxJtUsLrFDNACvgfwF7-kqChX_TDToWinbsFmHdAHlWOE4ePBJlHvgbdlPWefZpDNyBkidSRZ-mLfCkDuPmgwScn89Kw HTTP/1.1" 200 None
2025-04-09 14:11:08,815 - DEBUG - Starting new HTTPS connection (1): www.googleapis.com:443
2025-04-09 14:11:09,133 - DEBUG - https://www.googleapis.com:443 "GET /oauth2/v3/tokeninfo?id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImM3ZTA0NDY1NjQ5ZmZhNjA2NTU3NjUwYzdlNjVmMGE4N2FlMDBmZTgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIxMDQ3NDY0OTQxMjMwLTRmcDdwdjV1bTlsMHMydTBjMHNsaTV1czN2aDJ0bmtnLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiMTA0NzQ2NDk0MTIzMC00ZnA3cHY1dW05bDBzMnUwYzBzbGk1dXMzdmgydG5rZy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjExNjAzNTc2NTcyOTIxMjQzNTQ0NCIsImVtYWlsIjoiY29udGVudHBhZ2V3b3Jrc3BhY2UxQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYmYiOjE3NDQxODY4NjgsIm5hbWUiOiJIVWIgQWVyYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLZm1vUjE4VlNQd1NUbHZYQzdmOUVZZWlpeElrQWljZEdjNUJLcG92U0podk5pMlE9czk2LWMiLCJnaXZlbl9uYW1lIjoiSFViIiwiZmFtaWx5X25hbWUiOiJBZXJhIiwiaWF0IjoxNzQ0MTg3MTY4LCJleHAiOjE3NDQxOTA3NjgsImp0aSI6ImE3N2M5NDdlMzcwYWQ0N2M1ZDljM2UyOGFhYjcwYzhmN2M4NjA2MzAifQ.zx86ya2cPFWku97hvRf4E4C9X6yZ7OJVMfc5TWTpy8zj5q5CEHadycv_fyflBM60dWmelBGl4wL-Fbz-ErjjIc76yC5YAqlPUVDM4UR5shATJS-XUW8UoshUQ-vbj4sSmvP82yyHid3gL-6YI7DJIl6rlIK5ul72237BaEbUTRfufelgTiE59NaVUMZqIxBi1HcTB173H-QndaTPbm3Lx5jbqU6qxSjq7rI4xPwrIl2d7rMTM_KFCN0uFPVQr4sJkALsrpgFwFl9uTpJBrMqhY2CoH3iIiYJt5l__KyUcvNNShMNd1oh_J_G_dpnBWYq9vcWCDV9MRgdynIN7nlNSQ HTTP/1.1" 200 None
2025-04-09 14:11:58,742 - INFO - F:\funding app\backendServer\backendshop\User\GoogleLoginView.py changed, reloading.
2025-04-09 14:12:00,401 - INFO - Watching for file changes with StatReloader
2025-04-09 14:14:14,208 - DEBUG - Starting new HTTPS connection (1): www.googleapis.com:443
2025-04-09 14:14:14,557 - DEBUG - https://www.googleapis.com:443 "GET /oauth2/v3/tokeninfo?id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImM3ZTA0NDY1NjQ5ZmZhNjA2NTU3NjUwYzdlNjVmMGE4N2FlMDBmZTgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIxMDQ3NDY0OTQxMjMwLTRmcDdwdjV1bTlsMHMydTBjMHNsaTV1czN2aDJ0bmtnLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiMTA0NzQ2NDk0MTIzMC00ZnA3cHY1dW05bDBzMnUwYzBzbGk1dXMzdmgydG5rZy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjExNDc0OTk4OTg3NzkzMjcxNDM4MCIsImVtYWlsIjoicHJha2FzaG1haGFyYXl0OTgwQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYmYiOjE3NDQxODcwNTMsIm5hbWUiOiJBSSBsZWFybmVyIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0tpMVFIT3pyUXpOMjRSNTdPUmxiZ2Q3LTRGNnpuYVJQTXg1MmplY3BPRXNDa21NbUE9czk2LWMiLCJnaXZlbl9uYW1lIjoiQUkiLCJmYW1pbHlfbmFtZSI6ImxlYXJuZXIiLCJpYXQiOjE3NDQxODczNTMsImV4cCI6MTc0NDE5MDk1MywianRpIjoiZWZhMzE1MTBjNDVhY2I3Zjc0ZmM3ZjMwNzk3NzZkZTRhMjY0NDhjOSJ9.xl7ym7VqPAmbzuGDoIm9sTZewYwxQRlLxG5wa8Jt3t2CZ5FlCfPWrB3H2C05aS_ls3i47udbM785jeoT9qvNs-GQAljKS94_SyY2yRdnNe0HvdIuW4BPEVL7iUqRmS9HF1iPimz4CrPozWxriHmmBjLLDb7x6EsphLlBEzhjwc7-9HAFnU21TImA5G83RS-2szWh-CxW5WMUiTnmXLJG0rzyFj965Y7SDoeX2ME89bOgaMvCUyoWzHTGvFW3oc8snG0YqN1MdCrlpypEat8w1uVpIm9BsmWqvYU_wLWIl0F14UFnxRch0LxQ1ceNnlIvpzpmwbF3cRuGqAZp4R15qQ HTTP/1.1" 200 None
2025-04-09 14:14:43,670 - DEBUG - Starting new HTTPS connection (1): www.googleapis.com:443
2025-04-09 14:14:43,952 - DEBUG - https://www.googleapis.com:443 "GET /oauth2/v3/tokeninfo?id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImM3ZTA0NDY1NjQ5ZmZhNjA2NTU3NjUwYzdlNjVmMGE4N2FlMDBmZTgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIxMDQ3NDY0OTQxMjMwLTRmcDdwdjV1bTlsMHMydTBjMHNsaTV1czN2aDJ0bmtnLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiMTA0NzQ2NDk0MTIzMC00ZnA3cHY1dW05bDBzMnUwYzBzbGk1dXMzdmgydG5rZy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjExNjAzNTc2NTcyOTIxMjQzNTQ0NCIsImVtYWlsIjoiY29udGVudHBhZ2V3b3Jrc3BhY2UxQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYmYiOjE3NDQxODcwODMsIm5hbWUiOiJIVWIgQWVyYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLZm1vUjE4VlNQd1NUbHZYQzdmOUVZZWlpeElrQWljZEdjNUJLcG92U0podk5pMlE9czk2LWMiLCJnaXZlbl9uYW1lIjoiSFViIiwiZmFtaWx5X25hbWUiOiJBZXJhIiwiaWF0IjoxNzQ0MTg3MzgzLCJleHAiOjE3NDQxOTA5ODMsImp0aSI6IjRiYmE2ZmEzZWNiZGUyMjIyNDQzZjMyZTc1NGM2YWFjNDhhMWMwZTcifQ.MQ1e2vSdydD-kbNZW16F4y-KydtkdQ299bOaFXf6zseN0M6YDRsEkEvu4KbMsrbMpIKFHEwgJ1wOcht05lIhovk562bVeCMqMdm36VKeSFUPmRF-gLq8CIKZdgf1zXSS6RBdfcHZ_1HxcmHUTHWBaN3fuKelUapJaWxd5wa7_jSCNcIVglPpOA8HTX29Py5SwNSQuUbeJYSOjlWwxj9BWLGDdH9GHVs8xy4gHuJefUDMgAC1a9joZHdSSUuou0kLnBZEYo1AGpve7zgTOXpKfv-_hwsOazjl_3jKeINy9wbJ-kVX-EnpymY7YeWfUGANzV2zF4LFEEJ0fXWb65O1zA HTTP/1.1" 200 None
2025-04-09 14:16:23,446 - DEBUG - Starting new HTTPS connection (1): www.googleapis.com:443
2025-04-09 14:16:23,752 - DEBUG - https://www.googleapis.com:443 "GET /oauth2/v3/tokeninfo?id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImM3ZTA0NDY1NjQ5ZmZhNjA2NTU3NjUwYzdlNjVmMGE4N2FlMDBmZTgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIxMDQ3NDY0OTQxMjMwLTRmcDdwdjV1bTlsMHMydTBjMHNsaTV1czN2aDJ0bmtnLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiMTA0NzQ2NDk0MTIzMC00ZnA3cHY1dW05bDBzMnUwYzBzbGk1dXMzdmgydG5rZy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjExNjAzNTc2NTcyOTIxMjQzNTQ0NCIsImVtYWlsIjoiY29udGVudHBhZ2V3b3Jrc3BhY2UxQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYmYiOjE3NDQxODcxODIsIm5hbWUiOiJIVWIgQWVyYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLZm1vUjE4VlNQd1NUbHZYQzdmOUVZZWlpeElrQWljZEdjNUJLcG92U0podk5pMlE9czk2LWMiLCJnaXZlbl9uYW1lIjoiSFViIiwiZmFtaWx5X25hbWUiOiJBZXJhIiwiaWF0IjoxNzQ0MTg3NDgyLCJleHAiOjE3NDQxOTEwODIsImp0aSI6IjZkOGY4MzMyZjRjM2Q1OWI5MDFkZDVhMjI2NzEwMTdmODcyMzIyOGYifQ.ej9Yxl8YV2yylGxbyuKA7QTIrsXF54HWx0jOWGS9VULZiBwThbk3V7lf5qw1oBa42K_gouwP33GfvVsQ9kdNgt6kIzhZPwMXTDOlo5p9rec-UTH2FY73W6z3ec1hcFxVoDSMzgsc4hNtBLIK2VPYtxZ9IcVAB482BtqpRMWrGZGLCuSMXVMbxuhMQ8GW3-X1kD2BnKXWSeAOXk4gILo8ZJFjyyWpb77Ogc9p3HWjVFfbnpTa-yLjQGfwXfXTl9UvgXKP1_CT8SB_JvVp8mW0HYr7s1K7WatJJnSkZ83fCpFeedHjFg8XgHNBAMsCkIkkG_y7VDw3VxGPThT3fwpKiQ HTTP/1.1" 200 None
2025-04-09 14:18:38,152 - DEBUG - Starting new HTTPS connection (1): www.googleapis.com:443
2025-04-09 14:18:38,440 - DEBUG - https://www.googleapis.com:443 "GET /oauth2/v3/tokeninfo?id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImM3ZTA0NDY1NjQ5ZmZhNjA2NTU3NjUwYzdlNjVmMGE4N2FlMDBmZTgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIxMDQ3NDY0OTQxMjMwLTRmcDdwdjV1bTlsMHMydTBjMHNsaTV1czN2aDJ0bmtnLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiMTA0NzQ2NDk0MTIzMC00ZnA3cHY1dW05bDBzMnUwYzBzbGk1dXMzdmgydG5rZy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjExNjAzNTc2NTcyOTIxMjQzNTQ0NCIsImVtYWlsIjoiY29udGVudHBhZ2V3b3Jrc3BhY2UxQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYmYiOjE3NDQxODczMTcsIm5hbWUiOiJIVWIgQWVyYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NLZm1vUjE4VlNQd1NUbHZYQzdmOUVZZWlpeElrQWljZEdjNUJLcG92U0podk5pMlE9czk2LWMiLCJnaXZlbl9uYW1lIjoiSFViIiwiZmFtaWx5X25hbWUiOiJBZXJhIiwiaWF0IjoxNzQ0MTg3NjE3LCJleHAiOjE3NDQxOTEyMTcsImp0aSI6ImQwNTAxOTdkODRmMmE0MWVlZjllZTcxZWFlYzc2OGFlMjkxMGVjYmYifQ.TtH7_arw6rSAqsbNdMZHhsb5_T8ojnm2x1WXH8mBeGIiENPB_wpESagBJ4WmUz9SyRbWscKz5MxVum8h6uNEEpOgtz102rM92zeyvdIUwWJ-Z1frvY38sRGNrTF5ZrFJpUAbow3VrW82K1yJ_guQUzj1IEC7nxJuaeVpQXCyk5vyutZYjAvCMOD3tkBfrMiFeWJTvpOEapb59gIvJciuu3mymfWl-OuA_4XQa8KXxWkmLCl0JsGUnQwO3osXObDvKcigltAGeGJMgh026jiXV34v9mInfZUtMRj6-E3ejMytzoxlYPyyDbbhS00mJOVcoV5jSJITZS0cTHaKHgl2LA HTTP/1.1" 200 None
